title: Leiri 2020
description: Leirisivu 2020
baseurl: "/leiri2020"
url: "https://millakortelainen.github.io/leiri2020/"

markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true
sass:
    style: compact # possible values: nested expanded compact compressed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
